<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 class="title"><?= $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="post-list clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
        <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
            ?>
        <li class="post-holder post-holder-<?= (int)$_post->getId() ?>">


            <div class="post-content">
                <div class="post-description clearfix">
                    <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                    <?php if ($featuredImage) { ?>
                    <?php
                                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                            if (!$featuredImgAlt) {
                                $featuredImgAlt = $_postName;
                            }
                            ?>
                    <div class="post-ftimg-hld">
                        <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                            <img src="<?= $block->escapeHtml($featuredImage) ?>"
                                alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                        </a>
                    </div>
                    <div class="post-header">

                        <div class="post-title-holder clearfix">
                            <div class="post-title">
                                <a class="post-item-link" href="<?= /*@noEscape*/ $_postUrl ?>">
                                    <?= /*@noEscape*/ $_postName ?>
                                </a>
                            </div>
                        </div>

                        <div class="post-info clear">
                            <?php if ($_post->isPublishDateEnabled()) { ?>
                            <div class="item post-posed-date">
                                <span class="label"><?= $block->escapeHtml(__('Posted:')) ?></span>
                                <span
                                    class="value"><?= $block->escapeHtml(date('d-M-Y', strtotime($_post->getPublishDate()))) ?></span>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <?php } ?>
                    <div class="post-text-hld test clearfix">
                        <?= /*@noEscape*/ $block->getShorContent($_post) ?>
                    </div>
                </div>
            </div>
            <div class="post-footer">

            </div>
        </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>