<?php
/*
 * Maksym Lizohub theme
 * add "select2", <div class="toolbar-wrapper">
 * replace sorter.phtml / amount.phtml
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
<?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
<div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
    <?php if ($block->getIsBottom()): ?>
    <?= $block->getPagerHtml() ?>
    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
    <?php else: ?>
    <?php if ($block->isExpanded()): ?>
    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
    <?php endif ?>
    <div class="toolbar-wrapper">
        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php if ($block->isExpanded()): ?>
        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
    </div>
    <?php endif ?>
    <?php endif ?>
</div>
<?php endif ?>

<script type="text/javascript">
require(['jquery', 'select2', 'domReady!'], function($) {
    $('.sorter-options').select2({});
});
</script>