<?php
/**
 *Remove <label class="label" for="limiter"> ,  <span class="limiter-text"><?= $block->escapeHtml(__('per page')) ?></span>
*/
?>
<?php
/**
 * Product list toolbar
 *
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
?>
<div class="field limiter">

    <div class="control">
        <select id="limiter" data-role="limiter" class="limiter-options">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit):?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>" <?php if ($block->isLimitCurrent($_key)):?>
                selected="selected" <?php endif ?>>
                <?= $block->escapeHtml($localeFormatter->formatNumber((int) $_limit)) ?>
            </option>
            <?php endforeach; ?>
        </select>
    </div>

</div>