<?php
/**
 * Change text data
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
<?php if ($_product->isAvailable()) :?>
<div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
    <span><?= $block->escapeHtml(__('Availability: In stock')) ?></span>
</div>
<?php else :?>
<div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
    <span><?= $block->escapeHtml(__('Availability: Out of stock')) ?></span>
</div>
<?php endif; ?>
<?php endif; ?>